# Generated by Django 4.1.2 on 2022-10-20 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
                ('ingredients_txt', models.TextField()),
                ('image_img', models.ImageField(upload_to='')),
                ('description_txt', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
