# Generated by Django 3.2.16 on 2022-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_generator', '0002_recipe_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_img',
            field=models.BinaryField(),
        ),
    ]
